# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/cocoapods/specs'

target 'getSensor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for getSensor
  pod 'TwilioVoice', '~> 6.3.0'

  target 'getSensorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'getSensorUITests' do
    # Pods for testing
  end

end
